version: '3.8'
services:
  backend:
    build:
      context: .
    image: knagzaoh79/backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongo
    networks:
      - express-mongo
    expose:
      - 3000

  mongo:
    image: mongo:4.2.0
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  express-mongo:

volumes:
  mongo_data:
